- name: install Php5
  apt: pkg={{ item }} state=latest
  with_items:
    - php5
    - php5-mysql

- name: install php5-* extensions
  apt: pkg={{ item }} state=latest
  with_items:
    - libapache2-mod-php5
    - php5-cli
    - php5-cgi
    - php5-fpm
    - php5-common
    - php5-mysql
    - php5-gd
    - php5-curl
    - php5-intl
    - php5-mcrypt





